CREATE DATABASE WEBSITE

CREATE TABLE CUCTOMER (ID INT, FIRSTNAME VARCHAR (30), LASTNAME VARCHAR (30), EMAIL VARCHAR (30), PASS_WORD VARCHAR (30), GENDER VARCHAR (1), DATE_BIRTH DATE, CITY VARCHAR (30), PHONE_NUMBERS INT)
ALTER TABLE CUCTOMER
ALTER COLUMN ID INT NOT NULL;
ALTER TABLE CUCTOMER
ADD CONSTRAINT CUSTOMER_ID PRIMARY KEY (ID)
;
CREATE TABLE EMPLOYEE ( ID INT, FIRSTNAME VARCHAR (30), LASTNAME VARCHAR(30), POSITION VARCHAR (30), DATE_EMPLOYMENT DATE, ID_BOSS INT, RATE INT, BONUS INT)
ALTER TABLE EMPLOYEE
ALTER COLUMN ID INT NOT NULL;
ALTER TABLE EMPLOYEE 
ADD CONSTRAINT EMPLOYEE_ID PRIMARY KEY (ID);

CREATE TABLE CATEGORY ( ID INT, TYPY_OF_BOOK VARCHAR(15),AUTHOR VARCHAR (50), PUBLICATION VARCHAR(30), LANGUAGE_BOOK VARCHAR (15))
ALTER TABLE CATEGORY
ALTER COLUMN ID INT NOT NULL;
ALTER TABLE CATEGORY 
ADD CONSTRAINT CATEGORY_ID PRIMARY KEY (ID);


CREATE TABLE BOOK (ID INT, NAME VARCHAR(30), CATEGORY_ID INT, YEAR_PUBLICATION DATE, DESCRIPTION_BOOK VARCHAR(100),PRICE INT)
ALTER TABLE BOOK
ALTER COLUMN ID INT NOT NULL;
ALTER TABLE BOOK 
ADD CONSTRAINT BOOK_ID PRIMARY KEY (ID);

CREATE TABLE ORDERS ( ID INT, BOOK_ID INT,EMPLOYEE_ID INT, CUSTOMER_ID INT, NUMBERS INT, DATE_ORDER DATE, AMOUNT INT)

ALTER TABLE ORDERS ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUCTOMER(ID);
ALTER TABLE ORDERS ADD FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID);
ALTER TABLE ORDERS ADD FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID);
ALTER TABLE BOOK ADD FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID);
