CREATE DATABASE WEBSITE

CREATE TABLE OFFICE (ID INT, NAME VARCHAR (30), CITY VARCHAR (30), STREET VARCHAR(30), PHONE_NUMBER INT, EMAIL VARCHAR (30))
ALTER TABLE OFFICE
ALTER COLUMN ID INT NOT NULL;
ALTER TABLE OFFICE
ADD CONSTRAINT OFFICE_ID PRIMARY KEY (ID);

CREATE TABLE CUCTOMER (ID INT, FIRSTNAME VARCHAR (30), LASTNAME VARCHAR (30), EMAIL VARCHAR (30), PASS_WORD VARCHAR (30), GENDER VARCHAR (1), DATE_BIRTH DATE, CITY VARCHAR (30), PHONE_NUMBERS INT)
ALTER TABLE CUCTOMER
ALTER COLUMN ID INT NOT NULL;
ALTER TABLE CUCTOMER
ADD CONSTRAINT CUSTOMER_ID PRIMARY KEY (ID)
;
CREATE TABLE EMPLOYEE ( ID INT, FIRSTNAME VARCHAR (30), LASTNAME VARCHAR(30), POSITION VARCHAR (30), DATE_EMPLOYMENT DATE, RATE INT)
ALTER TABLE EMPLOYEE
ALTER COLUMN ID INT NOT NULL;
ALTER TABLE EMPLOYEE 
ADD CONSTRAINT EMPLOYEE_ID PRIMARY KEY (ID);
ALTER TABLE EMPLOYEE DROP COLUMN ID_BOSS
ALTER TABLE EMPLOYEE DROP COLUMN BONUS
ALTER TABLE EMPLOYEE ADD OFFICE_ID INT

CREATE TABLE CATEGORY ( ID INT, TYPY_OF_BOOK VARCHAR(15))
ALTER TABLE CATEGORY
ALTER COLUMN ID INT NOT NULL;
ALTER TABLE CATEGORY 
ADD CONSTRAINT CATEGORY_ID PRIMARY KEY (ID);
ALTER TABLE CATEGORY DROP COLUMN AUTHOR, PUBLICATION, LANGUAGE_BOOK;
ALTER TABLE CATEGORY ALTER COLUMN TYPY_OF_BOOK VARCHAR (40)
ALTER TABLE CATEGORY  ADD LANGUAGE_BOOK VARCHAR (30);
ALTER TABLE CATEGORY ADD FORMAT_BOOK VARCHAR (30);

CREATE TABLE AUTHOR (ID INT, FIRSTNAME VARCHAR (30), LASTNAME VARCHAR (30), DATE_BIRTH DATE)
ALTER TABLE AUTHOR
ALTER COLUMN ID INT NOT NULL;
ALTER TABLE AUTHOR 
ADD CONSTRAINT AUTHOR_ID PRIMARY KEY (ID);

CREATE TABLE PUBLICATION (ID INT, NAME VARCHAR(30))
ALTER TABLE PUBLICATION
ALTER COLUMN ID INT NOT NULL;
ALTER TABLE PUBLICATION 
ADD CONSTRAINT PUBLICATION_ID PRIMARY KEY (ID);
ALTER TABLE PUBLICATION ADD LOCATION VARCHAR(30), EMAIL VARCHAR (30), PHONE_NUMBERS INT; 
ALTER TABLE PUBLICATION ALTER COLUMN NAME VARCHAR (50)

CREATE TABLE BOOK (ID INT, NAME VARCHAR(30), CATEGORY_ID INT, AUTHOR_ID INT, PUBLICATION_ID INT, YEAR_PUBLICATION DATE, DESCRIPTION_BOOK VARCHAR(100),PRICE INT)
ALTER TABLE BOOK
ALTER COLUMN ID INT NOT NULL;
ALTER TABLE BOOK 
ADD CONSTRAINT BOOK_ID PRIMARY KEY (ID)
ALTER TABLE BOOK ADD AUTHOR_ID INT, PUBLICATION_ID INT
ALTER TABLE BOOK ALTER COLUMN NAME VARCHAR (60)

CREATE TABLE ORDERS ( ID INT, BOOK_ID INT,EMPLOYEE_ID INT, CUSTOMER_ID INT, NUMBERS INT, DATE_ORDER DATE, AMOUNT INT)

ALTER TABLE ORDERS ADD FOREIGN KEY (CUSTOMER_ID) REFERENCES CUCTOMER(ID);
ALTER TABLE ORDERS ADD FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID);
ALTER TABLE ORDERS ADD FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID);
ALTER TABLE BOOK ADD FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID);
ALTER TABLE BOOK ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID);
ALTER TABLE BOOK ADD FOREIGN KEY (PUBLICATION_ID) REFERENCES PUBLICATION(ID);
ALTER TABLE EMPLOYEE ADD FOREIGN KEY (OFFICE_ID) REFERENCES OFFICE(ID);