USE WEBSITE

-- Перегляд наступної інформації про книги: назва, автор, ціна --
SELECT NAME, FIRSTNAME, LASTNAME, PRICE 
FROM BOOK, AUTHOR
WHERE AUTHOR_ID=AUTHOR.ID

-- Перегляд усіх книг, що належать до різновиду літератири Х --
SELECT NAME
FROM BOOK, CATEGORY
WHERE CATEGORY_ID=CATEGORY.ID
AND TYPY_OF_BOOK IN ('Художня література')

-- Перегляд книг написаних мовою Х --
SELECT NAME
FROM BOOK, CATEGORY
WHERE CATEGORY_ID=CATEGORY.ID
AND LANGUAGE_BOOK IN ('Німецька')

-- Перегляд книг, що мають формат Х --
SELECT NAME
FROM BOOK, CATEGORY
WHERE CATEGORY_ID=CATEGORY.ID
AND FORMAT_BOOK IN ('Електронна')

-- Список книг, які найчасті купляли клієнти в Х році --

SELECT NAME, COUNT(*) AS COUNT_BOOK
FROM BOOK JOIN ORDERS
ON BOOK_ID=BOOK.ID
JOIN CUCTOMER ON CATEGORY_ID=CUCTOMER.ID
WHERE YEAR(DATE_ORDER)=2020
GROUP BY NAME
ORDER BY COUNT_BOOK DESC

-- Cписок усії книг, які купив покупець Х і скільки він заплатив--
SELECT FIRSTNAME, LASTNAME, NAME, SUM(AMOUNT) AS TOTAL_PRICE
FROM CUCTOMER JOIN ORDERS
ON CUSTOMER_ID=CUCTOMER.ID
JOIN BOOK ON BOOK_ID=BOOK.ID
WHERE CUCTOMER.ID=5
GROUP BY FIRSTNAME, LASTNAME, NAME

--Рейтинг категорій--
SELECT TYPY_OF_BOOK, SUM(NUMBERS) AS TOTAL_NUMBERS  
FROM BOOK JOIN CATEGORY
ON CATEGORY_ID=CATEGORY.ID
JOIN ORDERS ON BOOK.ID=BOOK_ID
GROUP BY TYPY_OF_BOOK
ORDER BY TOTAL_NUMBERS DESC

SELECT TYPY_OF_BOOK, LANGUAGE_BOOK, FORMAT_BOOK, SUM(NUMBERS) AS TOTAL_NUMBERS  
FROM BOOK JOIN CATEGORY
ON CATEGORY_ID=CATEGORY.ID
JOIN ORDERS ON BOOK.ID=BOOK_ID
GROUP BY TYPY_OF_BOOK, LANGUAGE_BOOK, FORMAT_BOOK
ORDER BY TOTAL_NUMBERS DESC

-- Список клієнтів, які купляли в магазині більше 5 разів--
SELECT FIRSTNAME, LASTNAME, COUNT(*) AS ORDERS_COUNT
FROM CUCTOMER JOIN ORDERS
ON CUSTOMER_ID=CUCTOMER.ID
GROUP BY FIRSTNAME, LASTNAME
HAVING COUNT(*) > 5


--РОЗШИРЕНЕ ЗАВДАННЯ--


-- Кількість проданих книг Х автора у У році--
SELECT  NAME, COUNT(*) AS NUMBER_ORDERS
FROM AUTHOR JOIN BOOK
ON AUTHOR_ID=AUTHOR.ID
JOIN ORDERS ON BOOK_ID=BOOK.ID
WHERE LASTNAME ='Костенко' AND YEAR(DATE_ORDER)=2021
GROUP BY NAME

--Прізвище, ім’я автора книги якого були куплені більше 5 разів--
SELECT FIRSTNAME, LASTNAME, COUNT (NUMBERS) AS COUNT_NUMBERS
FROM AUTHOR JOIN BOOK
ON AUTHOR_ID=AUTHOR.ID
JOIN ORDERS ON BOOK_ID=BOOK.ID
GROUP BY FIRSTNAME, LASTNAME
HAVING COUNT (NUMBERS)>5

--Статистика замовлень книжок в різні міста України--

SELECT CITY, COUNT(*) AS ORDERS_COUNT
FROM BOOK JOIN ORDERS
ON BOOK_ID=ORDERS.ID
JOIN CUCTOMER ON CUSTOMER_ID=ORDERS.ID
GROUP BY CITY
-- Статистика продажу книжок різних категорій--

SELECT TYPY_OF_BOOK, LANGUAGE_BOOK, FORMAT_BOOK, COUNT(*) AS ORDERS_COUNT
FROM CATEGORY JOIN BOOK
ON CATEGORY_ID=CATEGORY.ID
JOIN ORDERS ON BOOK_ID=BOOK.ID
GROUP BY TYPY_OF_BOOK, LANGUAGE_BOOK, FORMAT_BOOK

-- Показати книги, які ніхто не купив--
SELECT NAME
FROM BOOK
WHERE NOT EXISTS(
SELECT * FROM ORDERS
WHERE BOOK_ID=BOOK.ID)


-- Показати список клієнтів, в яких сума покупки перевищує 1000 грн --
SELECT FIRSTNAME, LASTNAME, ЗАГАЛЬНА_СУМА_ПОКУПКИ
FROM 
(SELECT FIRSTNAME, LASTNAME, SUM(AMOUNT) AS  ЗАГАЛЬНА_СУМА_ПОКУПКИ
FROM CUCTOMER JOIN ORDERS
ON CUSTOMER_ID=CUCTOMER.ID
GROUP BY FIRSTNAME, LASTNAME
) AS ПІДСУМКИ
WHERE ЗАГАЛЬНА_СУМА_ПОКУПКИ>1000

-- Статистика продажу книг різних видавнивницт по роках--
SELECT YEAR_ORDER, NAME, КІЛЬКІСТЬ_ЗАМОВЛЕНЬ, СУМА_ЗАМОВЛЕНЬ
FROM(SELECT YEAR(DATE_ORDER) AS YEAR_ORDER, PUBLICATION.NAME AS NAME, SUM(NUMBERS) AS [КІЛЬКІСТЬ_ЗАМОВЛЕНЬ], SUM(AMOUNT) AS [СУМА_ЗАМОВЛЕНЬ]
FROM PUBLICATION JOIN BOOK
ON PUBLICATION_ID=PUBLICATION.ID
JOIN ORDERS ON BOOK_ID=BOOK.ID
GROUP BY PUBLICATION.NAME, YEAR(DATE_ORDER))
AS ПІДСУМКИ

-- Статистика продажу книг в різні міста в Х році--
SELECT YEAR_ORDER, CITY, КІЛЬКІСТЬ_ЗАМОВЛЕНЬ, СУМА_ЗАМОВЛЕНЬ
FROM(SELECT YEAR(DATE_ORDER) AS YEAR_ORDER, CITY, SUM(NUMBERS) AS [КІЛЬКІСТЬ_ЗАМОВЛЕНЬ], SUM(AMOUNT) AS [СУМА_ЗАМОВЛЕНЬ]
FROM CUCTOMER JOIN ORDERS
ON CUSTOMER_ID=CUCTOMER.ID
WHERE YEAR(DATE_ORDER)=2021
GROUP BY CITY, YEAR(DATE_ORDER) )
AS ПІДСУМКИ

-- Скільки книг продав кожен працівник--
SELECT FIRSTNAME, LASTNAME, TOTAL
FROM(SELECT FIRSTNAME, LASTNAME, SUM(NUMBERS) AS TOTAL
FROM
EMPLOYEE JOIN ORDERS
ON EMPLOYEE_ID=EMPLOYEE.ID
GROUP BY FIRSTNAME, LASTNAME) AS ПІДСУМОК

